### PR TITLE
SubSampleShift: resample to interp1

### PR DESCRIPTION
**Pull request by petersaj**
SubSampleShift previously used resample, which uses filtering and was seen to sometimes cause a huge error in the last sample, which turned into a large artifact in the total signal after further filtering. This version uses linear interpolation and the original last data point.

### CODE REVIEW

**Comment by nsteinme** [comment]
Actually @kdharris101 wrote this SubSampleShift function - Kenneth do you recall whether the use of 'resample' rather than 'interp1' was important, or do you have an opinion about that now? Andy would like to change it to interp1 for reasons described above.

**Comment by kdharris101** [comment]
It was a long time ago! If I remember right, this decision was because I thought resample would play nicer with SVD transforms. But any linear method ought to work, and I believe interp1 with ‘cubic’ option is a linear operation.

So: try it and see if it works.

**Comment by petersaj** [comment]
I realized that the massive artifact I was getting was from something else,
but anyway here's an illustration of where I found it, this is the first
component over time and the problem point is the very last one:

total trace:
[image: image.png]

random segment in the middle:
[image: image.png]

end:
[image: image.png]

doesn't look like much is different between linear and cubic - matlab says
the cubic method is going to change in the future though, and linear
interpolation seems generally safer? but we can make it cubic if it would
be better for some reason

**Comment by kdharris101** [comment]
Not seeing those images inline. 

Can you clarify: is there a problem with using resample, or not? If no problem, let's not change it!

Another reason for preferring this resampling method is optimal for band-limited signals, whereas interpolation has many different methods that have different plusses and minuses in different situations. For example, linear interpolation can't ever produce a singal at any timepoint that exceeds the sampled timepoints - but resample can, and this is often appropriate. 

The most important question though is what works in practice. If there is a problem with resample, and interp1 fixes it, let's change it. Otherwise, let's not.

**Comment by petersaj** [comment]
I've attached the matlab figure (subsampleshift_fig), that's the first V
component with the different methods

actually I was wrong, the problem is my own: I high-pass filter the signal
using 'filtfilt' because it's zero-lag, whereas I think you guys used to
use 'filter'. I never noticed a problem with this before, but you can see
the difference in how it handles that wonky last point in the attached
filter_methods. I changed to filtfilt ages ago because I think I remember
seeing that there was a noticeable lag, but I can't see it in the attached
example, so I don't know what the motivation was exactly.

so: yes it's a big problem for me, but either the SubSampleShift can be
changed, or I can change my filter method, if you happen to know the
differences and might have a recommendation

**Pull request closed without merging**
